name: 'Zero Infra Mod Registry'
description: 'Manage mod repositories, dependencies, and releases using Docker (no dependencies required)'
author: 'Jacob Barber'
branding:
  icon: 'package'
  color: 'blue'

inputs:
  command:
    description: 'Command to execute (init, process-registry-updates, add, remove, validate)'
    required: true
  repo_url:
    description: 'Repository URL (required for init, add, and remove commands)'
    required: false
    default: ''
  release_tag:
    description: 'Release tag (required for add command)'
    required: false
    default: ''
  dry_run:
    description: 'Run in dry-run mode without making changes'
    required: false
    default: 'false'
  github_token:
    description: 'GitHub token for API access'
    required: true
    default: ${{ github.token }}
  log_level:
    description: 'Logging level (DEBUG, INFO, WARNING, ERROR, CRITICAL)'
    required: false
    default: 'INFO'
  registry_path:
    description: 'Path to the registry directory'
    required: false
    default: './registry'
  package_db_path:
    description: 'Path to the package database directory'
    required: false
    default: './package_db'

outputs:
  result:
    description: 'Output log from the command execution'
    value: ${{ steps.run-command.outputs.result }}
  failed:
    description: 'Whether the command failed or not'
    value: ${{ steps.run-command.outputs.failed }}

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}
    - ${{ inputs.repo_url }}
    - ${{ inputs.release_tag }}
  env:
    GITHUB_TOKEN: ${{ inputs.github_token }}
    LOG_LEVEL: ${{ inputs.log_level }}
    REGISTRY_PATH: ${{ inputs.registry_path }}
    PACKAGE_DB_PATH: ${{ inputs.package_db_path }}
    DRY_RUN: ${{ inputs.dry_run }}
