name: Example Usage of Zero Infra Mod Registry

# This is an example workflow showing how to use the Zero Infra Mod Registry as a GitHub Action
# This workflow is not meant to be run automatically - it's provided as an example only

on:
  # Manually trigger this workflow
  workflow_dispatch:
    inputs:
      command:
        description: 'Command to execute'
        required: true
        type: choice
        options:
          - init
          - process-registry-updates
          - add
          - remove
      repo_url:
        description: 'Repository URL (for init, add, remove commands)'
        required: false
        type: string
      release_tag:
        description: 'Release tag (for add command)'
        required: false
        type: string
      dry_run:
        description: 'Run in dry-run mode'
        required: false
        type: boolean
        default: true

jobs:
  run-registry-command:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed for making changes to repo
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Execute mod registry command
        uses: ./  # Use local action
        with:
          command: ${{ github.event.inputs.command }}
          repo_url: ${{ github.event.inputs.repo_url }}
          release_tag: ${{ github.event.inputs.release_tag }}
          dry_run: ${{ github.event.inputs.dry_run }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          log_level: 'INFO'
      
      # Only run if not in dry-run mode and there were changes
      - name: Commit changes
        if: ${{ github.event.inputs.dry_run == 'false' }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update mod registry - ${{ github.event.inputs.command }}"
          file_pattern: "registry/ package_db/"
