name: Auto Update Registry

on:
  push:
    branches:
      - main
    paths:
      - 'registry/**'
  
  # Allow manual triggering
  workflow_dispatch:

jobs:
  update-registry:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed for making changes to repo
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Process registry updates
        uses: ./  # Use local action
        with:
          command: process-registry-updates
          github_token: ${{ secrets.GITHUB_TOKEN }}
          log_level: 'INFO'
      
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto-update mod registry"
          file_pattern: "package_db/"
